// @flow
export const FETCH_RECEIVED_EVENTS_REQUEST = 'FETCH_RECEIVED_EVENTS_REQUEST';
export const FETCH_RECEIVED_EVENTS_SUCCESS = 'FETCH_RECEIVED_EVENTS_SUCCESS';
export const FETCH_RECEIVED_EVENTS_FAILURE = 'FETCH_RECEIVED_EVENTS_FAILURE';

export const GET_CREDENTIALS_WITH_CODE_REQUEST = 'GET_CREDENTIALS_WITH_CODE_REQUEST';
export const GET_CREDENTIALS_WITH_CODE_SUCCESS = 'GET_CREDENTIALS_WITH_CODE_SUCCESS';
export const GET_CREDENTIALS_WITH_CODE_FAILURE = 'GET_CREDENTIALS_WITH_CODE_FAILURE';
