// flow-typed signature: 1e395fe93fda9d356bb3c0857d949ef1
// flow-typed version: <<STUB>>/@yasaichi/redux-api-middleware_v^2.0.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@yasaichi/redux-api-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@yasaichi/redux-api-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@yasaichi/redux-api-middleware/lib/CALL_API' {
  declare module.exports: any;
}

declare module '@yasaichi/redux-api-middleware/lib/errors' {
  declare module.exports: any;
}

declare module '@yasaichi/redux-api-middleware/lib/index' {
  declare module.exports: any;
}

declare module '@yasaichi/redux-api-middleware/lib/middleware' {
  declare module.exports: any;
}

declare module '@yasaichi/redux-api-middleware/lib/util' {
  declare module.exports: any;
}

declare module '@yasaichi/redux-api-middleware/lib/validation' {
  declare module.exports: any;
}

// Filename aliases
declare module '@yasaichi/redux-api-middleware/lib/CALL_API.js' {
  declare module.exports: $Exports<'@yasaichi/redux-api-middleware/lib/CALL_API'>;
}
declare module '@yasaichi/redux-api-middleware/lib/errors.js' {
  declare module.exports: $Exports<'@yasaichi/redux-api-middleware/lib/errors'>;
}
declare module '@yasaichi/redux-api-middleware/lib/index.js' {
  declare module.exports: $Exports<'@yasaichi/redux-api-middleware/lib/index'>;
}
declare module '@yasaichi/redux-api-middleware/lib/middleware.js' {
  declare module.exports: $Exports<'@yasaichi/redux-api-middleware/lib/middleware'>;
}
declare module '@yasaichi/redux-api-middleware/lib/util.js' {
  declare module.exports: $Exports<'@yasaichi/redux-api-middleware/lib/util'>;
}
declare module '@yasaichi/redux-api-middleware/lib/validation.js' {
  declare module.exports: $Exports<'@yasaichi/redux-api-middleware/lib/validation'>;
}
